# Generated by Django 2.0.4 on 2018-04-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpagegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='post_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
