# Generated by Django 2.0.4 on 2018-04-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpage_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='post_title',
        ),
    ]
