# Generated by Django 2.0.4 on 2018-04-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogpage_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='blogbanners'),
        ),
    ]
