# Generated by Django 2.0.4 on 2018-04-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180415_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='what',
            new_name='intro_about',
        ),
    ]
