# Generated by Django 2.0.4 on 2018-04-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_landingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='info_box_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_box_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_box_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_box_4',
            field=models.TextField(blank=True),
        ),
    ]
