# Generated by Django 2.0.4 on 2018-04-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180422_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='info_heading_1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_heading_2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_heading_3',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_heading_4',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
