# Generated by Django 2.0.4 on 2018-04-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180422_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro_about_image',
            field=models.ImageField(blank=True, upload_to='homepage'),
        ),
    ]
