# Generated by Django 2.0.4 on 2018-04-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepage_intro_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_banner',
            field=models.ImageField(blank=True, upload_to='homepage'),
        ),
    ]
