# Generated by Django 2.0.4 on 2018-04-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_hero_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='social_banner',
            field=models.ImageField(blank=True, upload_to='homepage'),
        ),
    ]
